export const ACTION_TYPES = {
  GENERATED_KEYS_LOADING: "GENERATED_KEYS_LOADING",
  GENERATED_KEYS_RESPONSE: "GENERATED_KEYS_RESPONSE",
  CREATEDACCOUNT: "CREATEDACCOUNT",
  CREATED_ACCOUNT_RESPONSE: "CREATED_ACCOUNT_RESPONSE",
  CONTRACT_CALL: "CONTRACTCALL",
  CONTRACT_CALL_RESPONSE: "CONTRACT_CALL_RESPONSE",
  APPROVE_OTP: "APPROVE_OTP",
  APPROVEOTP_RESPONSE: "APPROVEOTP_RESPONSE",
  SAVE_DOCUMENTS: "SAVE_DOCUMENTS",
};
