export const ACTION_TYPES = {
  GENERATED_KEYS_LOADING: "GENERATED_KEYS_LOADING",
  GENERATED_KEYS_RESPONSE: "GENERATED_KEYS_RESPONSE",
  GENERATED_KEYS_ERROR: "GENERATED_KEYS_ERROR",

  CREATEDACCOUNT: "CREATEDACCOUNT",
  CREATED_ACCOUNT_RESPONSE: "CREATED_ACCOUNT_RESPONSE",
  CREATED_ACCOUNT_ERROR: "CREATED_ACCOUNT_ERROR",

  CONTRACT_CALL: "CONTRACTCALL",
  CONTRACT_CALL_RESPONSE: "CONTRACT_CALL_RESPONSE",
  CONTRACT_CALL_ERROR: "CONTRACT_CALL_ERROR",

  APPROVE_OTP: "APPROVE_OTP",
  APPROVEOTP_RESPONSE: "APPROVEOTP_RESPONSE",
  APPROVEOTP_ERROR: "APPROVEOTP_ERROR",
  SAVE_DOCUMENTS: "SAVE_DOCUMENTS",
  UPDATE_DOCUMENTS: "UPDATE_DOCUMENTS",
  SAVE_SECURITY: "SAVE_SECURITY",

  SAVE_QR: "SAVE_QR",
  SAVE_PROFILE_PIC: "SAVE_PROFILE_PIC",

  CREATEDSCHEMA: "CREATEDSCHEMA",
  CREATED_SCHEMA_RESPONSE: "CREATED_SCHEMA_RESPONSE",
  CREATED_SCHEMA_ERROR: "CREATED_SCHEMA_ERROR",

  CREATEREGDOC:"CREATEREGDOC",
  CREATE_REGDOC_RESPONSE:"CREATE_REGDOC_RESPONSE",
  CREATE_REGDOC_ERROR:"CREATE_REGDOC_RESPONSE",

  GET_HISTORY_CALL: "GET_HISTORY_CALL",
  GET_HISTORY_CALL_RESPONSE: "GET_HISTORY_CALL_RESPONSE",
  GET_HISTORY_CALL_ERROR: "GET_HISTORY_CALL_ERROR",
};
