export const LocalImages = {
  homeImage: require("../../resources/images/user.png"),
  moreImage: require("../../resources/images/more.png"),
  historyImage: require("../../resources/images/history.png"),
  scanImage: require("../../resources/images/scan.png"),
  logoImage: require("../../resources/images/logo.png"),
  closeImage: require("../../resources/images/close.png"),
  logoutImage: require("../../resources/images/logout.png"),
  sideArrowImage: require("../../resources/images/sidearrow.png"),
  giftBoxImage: require("../../resources/images/gift-box.png"),
  humbergerImage: require("../../resources/images/humburger.png"),
  avatarImage: require("../../resources/images/avatar.png"),
  addImage: require("../../resources/images/add.png"),
  searchImage: require("../../resources/images/search.png"),
  menuImage: require("../../resources/images/menu.png"),
  filter: require("../../resources/images/filter.png"),
  upImage: require("../../resources/images/go-up.png"),
  documentsImage: require("../../resources/images/documents.png"),
  vcImage: require("../../resources/images/VC.png"),
  shareImage: require("../../resources/images/share.png"),
  deleteImage: require("../../resources/images/delete.png"),
  backImage: require("../../resources/images/back.png"),
  successTikImage: require("../../resources/images/sucessTik.png"),
  cameraImage: require("../../resources/images/camera.png"),
  //categories
  CATEGORIES: {
    travelImage: require("../../resources/images/travel.png"),
    educationImage: require("../../resources/images/education.png"),
    insuranceImage: require("../../resources/images/Insurence.png"),
    personalcardImage: require("../../resources/images/personalcard.png"),
  },
  SOCIAL_MEDIA_: {
    facebookImage: require("../../resources/images/facebook.png"),
    instagramImage: require("../../resources/images/instagram.png"),
    webImage: require("../../resources/images/world.png"),
    telegramImage: require("../../resources/images/telegram.png"),
    linkdInImage: require("../../resources/images/linkedIn.png"),
    twitterImage: require("../../resources/images/twitter.png"),
  },
};
