import { isEarthId } from "../utils/PlatFormUtils";
export const LocalImages = {
  homeImage: require("../../resources/images/user.png"),
  moreImage: require("../../resources/images/more.png"),
  email: require("../../resources/images/mail.png"),
  phone: require("../../resources/images/phone.png"),
  historyImage: require("../../resources/images/history.png"),
  scanImage: require("../../resources/images/scan.png"),
  logoImage: isEarthId()
    ? require("../../resources/images/earthIdLogo.png")
    : require("../../resources/images/logo.png"),
  recent: require("../../resources/images/norecentactivity.png"),
  closeImage: require("../../resources/images/close.png"),
  logoutImage: require("../../resources/images/logout.png"),
  sideArrowImage: require("../../resources/images/sidearrow.png"),
  down: require("../../resources/images/down.png"),
  giftBoxImage: require("../../resources/images/gift-box.png"),
  humbergerImage: require("../../resources/images/humburger.png"),
  avatarImage: require("../../resources/images/avatar.png"),
  addImage: require("../../resources/images/add.png"),
  searchImage: require("../../resources/images/search.png"),
  menuImage: require("../../resources/images/menu.png"),
  filter: require("../../resources/images/filter.png"),
  upImage: require("../../resources/images/go-up.png"),
  upload: require("../../resources/images/upload.png"),
  documentsImage: require("../../resources/images/documents.png"),
  vcImage: require("../../resources/images/VC.png"),
  shareImage: require("../../resources/images/share.png"),
  deleteImage: require("../../resources/images/delete.png"),
  backImage: require("../../resources/images/back.png"),
  successTikImage: require("../../resources/images/sucessTik.png"),
  cameraImage: require("../../resources/images/camera.png"),
  editImage: require("../../resources/images/edit.png"),
  galleryImage: require("../../resources/images/gallery.png"),
  calendarImage: require("../../resources/images/calendar.png"),
  tikImage: require("../../resources/images/tik.png"),
  settingsImage: require("../../resources/images/settings.png"),
  termsImage: require("../../resources/images/terms.png"),
  profileImage: require("../../resources/images/profile.png"),
  registerdocumentImage: require("../../resources/images/registerdocument.png"),
  qrcodeImage: require("../../resources/images/qr-code.png"),
  securityImage: require("../../resources/images/security.png"),
  faceImage: require("../../resources/images/face-id.png"),
  touchImage: require("../../resources/images/touch.png"),
  passcordImage: require("../../resources/images/passcord.png"),
  scanbarImage: require("../../resources/images/scanbarcode.png"),
  qrscanImage: require("../../resources/images/qrscan.png"),
  translateImage: require("../../resources/images/translate.png"),
  facedetection: require("../../resources/images/facedetection.png"),
  fingerprint: require("../../resources/images/fingerprint.png"),
  editIcon: require("../../resources/images/editIcon.png"),
  backupicon: require("../../resources/images/backupicon.png"),
  uploadqrimage: require("../../resources/images/uploadqrimage.png"),
  cam: require("../../resources/images/cam.png"),
  settingpic: require("../../resources/images/settingpic.png"),
  settingimage: require("../../resources/images/settingimage.png"),
  manualIcon: require("../../resources/images/manualIcon.png"),
  documentpic: require("../../resources/images/documentpic.png"),
  faceidpic: require("../../resources/images/faceidpic.png"),
  touchidpic: require("../../resources/images/touchidpic.png"),
  nexticon: require("../../resources/images/nexticon.png"),
  backicon: require("../../resources/images/backicon.png"),

  //categories
  CATEGORIES: {
    travelImage: require("../../resources/images/travel.png"),
    educationImage: require("../../resources/images/education.png"),
    insuranceImage: require("../../resources/images/Insurence.png"),
    personalcardImage: require("../../resources/images/personalcard.png"),
  },
  SOCIAL_MEDIA_: {
    facebookImage: require("../../resources/images/facebook.png"),
    instagramImage: require("../../resources/images/instagram.png"),
    webImage: require("../../resources/images/world.png"),
    telegramImage: require("../../resources/images/telegram.png"),
    linkdInImage: require("../../resources/images/linkedIn.png"),
    twitterImage: require("../../resources/images/twitter.png"),
  },
  LOTTIEICONS: {
    success: require("../../resources/lottie/31973-success-message.json"),
    loader: require("../../resources/lottie/load.json"),
  },
};
