export const LocalImages = {
  homeImage: require("../../resources/images/user.png"),
  moreImage: require("../../resources/images/more.png"),
  historyImage: require("../../resources/images/history.png"),
  scanImage: require("../../resources/images/scan.png"),
  logoImage: require("../../resources/images/logo.png"),
  closeImage: require("../../resources/images/close.png"),
  logoutImage: require("../../resources/images/logout.png"),
  sideArrowImage: require("../../resources/images/sidearrow.png"),
  giftBoxImage: require("../../resources/images/gift-box.png"),
  humbergerImage: require("../../resources/images/humburger.png"),
  avatarImage: require("../../resources/images/avatar.png"),
  addImage: require("../../resources/images/add.png"),
  searchImage: require("../../resources/images/search.png"),
  menuImage: require("../../resources/images/menu.png"),
  filter: require("../../resources/images/filter.png"),
  upImage: require("../../resources/images/go-up.png"),
  //categories
  CATEGORIES: {
    travelImage: require("../../resources/images/travel.png"),
    educationImage: require("../../resources/images/education.png"),
    insuranceImage: require("../../resources/images/Insurence.png"),
    personalcardImage: require("../../resources/images/personalcard.png"),
  },
};
