require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.2'
install! 'cocoapods', :deterministic_uuids => false

target 'EarthId' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'FaceDetectorMLKit'
]
pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'



  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'
  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'
  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'



  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'




  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

  target 'EarthIdTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
       installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
         end
       end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
 # Manually link packages here to keep your extension bundle size minimal
end
